const USER_ALREADY_EXIST = 'USER_ALREADY_EXIST'
const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST'
const PASSWORD_IS_INCORRECT = 'PASSWORD_IS_INCORRECT'
const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED'
const UNAUTHORIZED = 'UNAUTHORIZED'

module.exports = {
  AUTHORIZATION_FAILED,
  PASSWORD_IS_INCORRECT,
  USER_DOES_NOT_EXIST,
  USER_ALREADY_EXIST,
  UNAUTHORIZED
}